Repository clowder-framework/clowder2, pull requests merged in 2023-03, with the labels that each got.

#361 Updated File Is Wrong Size
  backend/app/routers/files.py
Labels: bug

#371 Added new Page Not Found component, updated route to use new component
  backend/app/routers/datasets.py
  frontend/src/actions/common.js
  frontend/src/components/errors/PageNotFound.tsx
  frontend/src/reducers/error.ts
  frontend/src/routes.tsx
  frontend/src/types/action.ts
Labels: enhancement, frontend

#362 348 metadata value not visible on UI
  backend/app/routers/metadata_files.py
  frontend/src/components/metadata/DisplayMetadata.tsx
  frontend/src/components/metadata/widgets/MetadataTextField.tsx
Labels: bug

#370 changing context to list in metadata defs
  scripts/metadata/definitions/alternativeTitle.json
  scripts/metadata/definitions/coordinates.json
  scripts/metadata/definitions/doi.json
  scripts/metadata/definitions/latLon.json
  scripts/metadata/definitions/time.json
  scripts/metadata/definitions/unit.json
Labels: backend

#341 adding restart unless stopped for this container
  docker-compose.dev.yml
Labels: bug

#387 add MetadataAuthorization dependency
  backend/app/deps/authorization_deps.py
  backend/app/routers/datasets.py
  backend/app/routers/metadata.py
  backend/app/routers/metadata_datasets.py
Labels: backend
